services:
  - type: web
    name: grocery-price-comparison-api
    runtime: docker
    region: oregon
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./data/grocery_prices.db
      - key: PORT
        value: 8000
    disk:
      name: grocery-data
      mountPath: /app/data
      sizeGB: 1

  - type: web
    name: grocery-price-comparison-frontend
    env: node
    region: oregon
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://grocery-price-comparison-api.onrender.com
