"""add_stores_locations_tables

Revision ID: b8c21cb5ea58
Revises: c121f1adb7f3
Create Date: 2026-02-06 04:54:14.424524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8c21cb5ea58'
down_revision: Union[str, None] = 'c121f1adb7f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if stores table exists before creating
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()
    
    if 'stores' not in existing_tables:
        op.create_table('stores',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_stores_id'), 'stores', ['id'], unique=False)
        op.create_index(op.f('ix_stores_name'), 'stores', ['name'], unique=True)
    
    if 'locations' not in existing_tables:
        op.create_table('locations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('store_id', sa.Integer(), nullable=False),
        sa.Column('external_store_id', sa.String(), nullable=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('address', sa.String(), nullable=True),
        sa.Column('suburb', sa.String(), nullable=True),
        sa.Column('state', sa.String(), nullable=True),
        sa.Column('postcode', sa.String(), nullable=True),
        sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
        sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
        sa.Column('phone', sa.String(), nullable=True),
        sa.Column('opening_hours', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('idx_location_coords', 'locations', ['latitude', 'longitude'], unique=False)
        op.create_index('idx_store_state_postcode', 'locations', ['store_id', 'state', 'postcode'], unique=False)
        op.create_index(op.f('ix_locations_external_store_id'), 'locations', ['external_store_id'], unique=False)
        op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
        op.create_index(op.f('ix_locations_is_active'), 'locations', ['is_active'], unique=False)
        op.create_index(op.f('ix_locations_latitude'), 'locations', ['latitude'], unique=False)
        op.create_index(op.f('ix_locations_longitude'), 'locations', ['longitude'], unique=False)
        op.create_index(op.f('ix_locations_postcode'), 'locations', ['postcode'], unique=False)
        op.create_index(op.f('ix_locations_state'), 'locations', ['state'], unique=False)
        op.create_index(op.f('ix_locations_store_id'), 'locations', ['store_id'], unique=False)
        op.create_index(op.f('ix_locations_suburb'), 'locations', ['suburb'], unique=False)
    
    # Check if columns exist before adding
    carts_columns = [c['name'] for c in inspector.get_columns('carts')]
    if 'location_id' not in carts_columns:
        op.add_column('carts', sa.Column('location_id', sa.Integer(), nullable=True))
        op.create_index(op.f('ix_carts_location_id'), 'carts', ['location_id'], unique=False)
        op.create_foreign_key(None, 'carts', 'locations', ['location_id'], ['id'], ondelete='SET NULL')
    
    products_columns = [c['name'] for c in inspector.get_columns('products')]
    if 'store_id' not in products_columns:
        op.add_column('products', sa.Column('store_id', sa.Integer(), nullable=True))
        op.create_index(op.f('ix_products_store_id'), 'products', ['store_id'], unique=False)
        op.create_foreign_key(None, 'products', 'stores', ['store_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_store_id'), table_name='products')
    op.drop_column('products', 'store_id')
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.drop_index(op.f('ix_carts_location_id'), table_name='carts')
    op.drop_column('carts', 'location_id')
    op.drop_index(op.f('ix_locations_suburb'), table_name='locations')
    op.drop_index(op.f('ix_locations_store_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_state'), table_name='locations')
    op.drop_index(op.f('ix_locations_postcode'), table_name='locations')
    op.drop_index(op.f('ix_locations_longitude'), table_name='locations')
    op.drop_index(op.f('ix_locations_latitude'), table_name='locations')
    op.drop_index(op.f('ix_locations_is_active'), table_name='locations')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_external_store_id'), table_name='locations')
    op.drop_index('idx_store_state_postcode', table_name='locations')
    op.drop_index('idx_location_coords', table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_stores_name'), table_name='stores')
    op.drop_index(op.f('ix_stores_id'), table_name='stores')
    op.drop_table('stores')
    # ### end Alembic commands ###
